---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube
  labels:
    app: sonarqube
spec:
  type: NodePort
  ports:
   - port: 9000
     nodePort: 31900
  selector:
   app: sonarqube