---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarqube
  namespace: sonarqube
  labels: 
    app: sonarqube
spec:
  selector:
    matchLabels:
      app: sonarqube
  serviceName: sonarqube
#Modify number of replicas if load balancer is used for high availability
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
        #Configure image version below if needed
          image: sonarqube:8.9-enterprise
          resources:
          #Configure resources to meet sq version requirements
            limits:
              cpu: 3000m
              memory: 16Gi
            requests:
              cpu: 2000m
              memory: 8Gi
          volumeMounts:
          - mountPath: "/opt/sonarqube/data/"
            name: sonar-data
          env:
          - name: "SONARQUBE_JDBC_USERNAME"
            valueFrom:
               secretKeyRef:
                 name: postgres-secrets
                 key: username
          - name: "SONARQUBE_JDBC_URL"
            valueFrom:
              configMapKeyRef:
                name: sonar-config
                key: url
          - name: "SONARQUBE_JDBC_PASSWORD"
            valueFrom:
               secretKeyRef:
                 name: postgres-secrets
                 key: password
          - name: "SONAR_SECURITY_REALM"   
            valueFrom:
              configMapKeyRef:
                name: sonar-config
                key: SONAR_SECURITY_REALM  
          - name: "LDAP_URL"   
            valueFrom:
              configMapKeyRef:
                name: sonar-config
                key: LDAP_URL 
          - name: "LDAP_USER_BASEDN"   
            valueFrom:
              configMapKeyRef:
                name: sonar-config
                key: LDAP_USER_BASEDN
          - name: "LDAP_USER_REQUEST"   
            valueFrom:
              configMapKeyRef:
                name: sonar-config
                key: LDAP_USER_REQUEST 
          - name: "LDAP_USER_EMAILATTRIBUTE"   
            valueFrom:
              configMapKeyRef:
                name: sonar-config
                key: LDAP_USER_EMAILATTRIBUTE                                                                             
          ports:
          - containerPort: 9000
            protocol: TCP
      volumes:
      - name: sonar-data
        persistentVolumeClaim:
          claimName: sonar-data
      nodeSelector:
        sonarqube: "true"
      tolerations:
        - key: "sonarqube"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"