---
- name: 'Postgres 13 deployment on Kubernetes cluster (SonarQube backend)'
  hosts: k8s-controlplane
  become: false
  tasks:
    - name: Apply K8s resources for postgres (SonarQube backend)
      kubernetes.core.k8s:
        definition: "{{ lookup('template', '{{ item }}') | from_yaml }}"
      with_fileglob:
        - "/root/sdo-kubernetes-cicd/ansible/k8s-yaml-defs/sonarqube/postgres-yaml-defs/postgres-secrets.yaml"
        - "/root/sdo-kubernetes-cicd/ansible/k8s-yaml-defs/sonarqube/postgres-yaml-defs/postgres-pv.yaml"
        - "/root/sdo-kubernetes-cicd/ansible/k8s-yaml-defs/sonarqube/postgres-yaml-defs/postgres-pvc.yaml"
        - "/root/sdo-kubernetes-cicd/ansible/k8s-yaml-defs/sonarqube/postgres-yaml-defs/postgres-svc.yaml"
        - "/root/sdo-kubernetes-cicd/ansible/k8s-yaml-defs/sonarqube/postgres-yaml-defs/postgres-sts.yaml"
