apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: sonarqube
type: Opaque
data:
  username: c29uYXI=
  password: ZXFYdjI5IQ==
  postgres_db: c29uYXJkYg==
  #postgres-0:5432:sonardb:postgres:postgres
  pgpass: cG9zdGdyZXMtMDo1NDMyOnNvbmFyZGI6cG9zdGdyZXM6cG9zdGdyZXM=