#!/bin/bash
#
# This script designed to backup postgresql for sonarqube
# v 1.0  - run with root privileges 

mkdir -p /var/lib/postgresql/sonar-backup/daily

kubectl exec -it -n sonarqube-test postgres-0 -- pg_dump -U sonar sonardb > /var/lib/postgresql/sonar-backup/monthly/sq-pg-backup-$(date +"%m-%d-%Y-%H-%M").sql

find /var/lib/postgresql/sonar-backup/daily/* -mtime +93 -delete
